### ISSUE TITLE
iOS 13.4.1

### ISSUE THREAD

**Issue by adamski** [haikieu/xcode-developer-disk-image-all-platforms#1]
If anyone has 13.4.1 and can add it here I would be most grateful. I just updated my device and I can't find a copy of the latest iOS disk image.

**Comment by eAi** [comment]
Likewise!

**Comment by haikieu** [comment]
> If anyone has 13.4.1 and can add it here I would be most grateful. I just updated my device and I can't find a copy of the latest iOS disk image.

The 13.4 image would work for 13.4.1. 
If it does work, you can try this trick: First duplicate the 13.4 directory, rename it to 13.4.1. This would work when you reopen XCode.

**Comment by adamski** [comment]
Thanks @haikieu , however that trick still does not work for me. Xcode tells me: 

> This iPhone 7 (Model 1660, 1778, 1779, 1780) is running iOS 13.4.1 (17E262), which may not be supported by this version of Xcode. An updated version of Xcode may be found on the App Store or at developer.apple.com.

**Comment by adamski** [comment]
I was somehow putting it in the wrong folder.. not sure how that happened, but I navigated via Xcode.app and found the correct folder, all working now.
