### ISSUE TITLE
iOS 15.1

### ISSUE THREAD

**Issue by SmileSydney** [haikieu/xcode-developer-disk-image-all-platforms#10]
Just wondering if this is in the works. Much appreciated1

**Comment by haikieu** [comment]
Unfortunately, I'm not managed to find iOS 15.1 image anywhere. The latest is iOS 15.2 (already available) from XCode 13.2 beta.
I think you can work around by rename the image of 15.2 to 15.1. That could have worked, good luck.

**Comment by acarolsf** [comment]
Não funcionou 😢

**Comment by haikieu** [comment]
Maybe you should upgrade your device to 15.2 instead. That version is available.
