### ISSUE TITLE
iOS 15.3?

### ISSUE THREAD

**Issue by SmileSydney** [haikieu/xcode-developer-disk-image-all-platforms#11]
Any chance this can be uploaded?

**Comment by mspvirajpatel** [comment]
> Any chance this can be uploaded?
 Please check out this repo : 
 [15.3 Disk Image & more](https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/15.3)

**Comment by haikieu** [comment]
The latest XCode does not supply the image for 15.3.
We can workaround by make use of 15.2 or 15.4, and rename them to 15.3
