### ISSUE TITLE
iOS 15.6.1

### ISSUE THREAD

**Issue by Zeafer** [haikieu/xcode-developer-disk-image-all-platforms#13]
iOS 15.6.1 and iPadOS 15.6.1
Released August 17, 2022

Required support files currently missing.

**Comment by mspvirajpatel** [comment]
https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/15.6.1 
@Zeafer

**Comment by haikieu** [comment]
Addressed in the latest comment
