### ISSUE TITLE
IOS 16.0.2

### ISSUE THREAD

**Issue by terrycj66** [haikieu/xcode-developer-disk-image-all-platforms#17]
Hi,

I recently upgraded my iPhone 13 Pro Max to iOS 16.0.2 and now when i try to "set fake location" i get the diskmount error.

I have rebooted my iMac (running macOS Monterey 12.6) and the iPhone and also reset the privacy/trust setting on the iPhone to ensure the trust relationship was in place to no avail.

I noted that some other disk-images had sub-releases and wonder if that is the issue?

The application automatically downloaded 16.0 as it had done in the past but something still isn't right...

Many Thanks

**Comment by ashlesh688** [comment]
Hi,

I have the same issue, I updated my IOS to 16.1 and this caused issue with mounting image. I checked iTunes and my mobile was recognized,  I encounter this error while mounting

"Mount failed with status: N/A and error: ImageMountFailed"

Thanks

**Comment by asahi0416** [comment]
Hi,

 i am also having the same problem

**Comment by haikieu** [comment]
Clear the device support from XCode cache at ~/Library/Developer/Xcode/iOS DeviceSupport
Then reconnect the device. Xcode will start over fetch the images from your device.
Hopefully this can help
