### ISSUE TITLE
ios 16.1または16,2でApple製品接続時のディスクイメージマウントエラーについて

### ISSUE THREAD

**Issue by asahi0416** [haikieu/xcode-developer-disk-image-all-platforms#18]
When I clicked the button to set a fake location, I got the error Unable to mount developer image. I tried to download directly from device support to find out the cause of the error, but there were only files up to ios16.0. Could you make an image for 16.1 or 16.2?

**Comment by haikieu** [comment]
Clear the device support from XCode cache at ~/Library/Developer/Xcode/iOS DeviceSupport
Then reconnect the device. Xcode will start over fetch the images from your device.
Hopefully this can help

**Comment by haikieu** [comment]
16.1 is available.
