### ISSUE TITLE
iPadOS 16.1 failed to set location with "Mount failed with status"

### ISSUE THREAD

**Issue by Lufthansa6264** [haikieu/xcode-developer-disk-image-all-platforms#19]
![QQ截图20230223183329](https://user-images.githubusercontent.com/98276119/220882776-5cc29f19-4e04-4654-8aa6-270aebbb809e.jpg)
Downloading the version of 16.1 in iPhoneOS, it displayed the error as pic.
When my iPad was 15.X, i can still use the image uploaded in iPhoneOS folder, but it didn't work after 16.X was updated.

**Comment by haikieu** [comment]
Clear the device support from XCode cache at ~/Library/Developer/Xcode/iOS DeviceSupport
Then reconnect the device. Xcode will start over fetch the images from your device.
Hopefully this can help
