### ISSUE TITLE
ios 14.1

### ISSUE THREAD

**Issue by ymmf80** [haikieu/xcode-developer-disk-image-all-platforms#2]
Is there a chance to get a developer image for this ios version please?

**Comment by triske007** [comment]
https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/14.1

**Comment by ymmf80** [comment]
> https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/14.1

Thank you! Much appreciated!
