### ISSUE TITLE
iOS 14.7

### ISSUE THREAD

**Issue by freddygreve** [haikieu/xcode-developer-disk-image-all-platforms#7]
Hey! Can anyone provide 14.7 image?

**Comment by aShrestha-Outcode** [comment]
yes please.... Can we have develop disc image 14.7

**Comment by mspvirajpatel** [comment]
- iOS 14.7 -> https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/14.7
 - iOS 14.7.1 -> https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/14.7.1

@freddygreve @aShrestha-Outcode

**Comment by haikieu** [comment]
Uploaded image for 14.7

**Comment by nanoscopic** [comment]
Shouldn't this still be open? 14.7.1 is not present.
